on:
  push:

name: Run Checks

jobs:
  build:
    name: Chia
    runs-on: ubuntu-latest
    container:
      image: worldiety/chia:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Run chia cli
        run: chia --config https://raw.githubusercontent.com/JulianKahnert/chia-config/master/chia.yml
